/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
  id("vanity.kotlin-library-conventions")
}

dependencies {

  implementation("io.github.microutils:kotlin-logging-jvm:3.0.4")
  implementation("ch.qos.logback:logback-classic:1.4.5")

  implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.6.4")

}
