/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
  id("easyreading.kotlin-library-conventions")
}

dependencies {

  implementation("io.github.microutils:kotlin-logging-jvm:2.0.11")
  implementation("ch.qos.logback:logback-classic:1.2.6")

  implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.6.4")

}
