/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package easyreading.app

import easyreading.app.failurewindows.showError
import easyreading.app.init.Init
import easyreading.app.init.inject.Koin
import easyreading.app.init.inject.getService
import javafx.application.Application
import javafx.scene.Group
import javafx.scene.Scene
import javafx.scene.shape.Circle
import javafx.stage.Stage
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.javafx.JavaFx
import kotlinx.coroutines.withContext

suspend fun main() = withContext(Dispatchers.JavaFx) {
    Koin().start()
    Init(getService(), { message -> showError(message) }) { startApps() }
    Unit
}

private fun startApps() {
    val fxApp = BionicReader()
    fxApp.start(Stage())
}

class BionicReader : Application() {
    override fun start(stage: Stage) {
        val circ = Circle(40.0, 40.0, 30.0)
        val root = Group(circ)
        val scene = Scene(root, 400.0, 300.0)
        stage.title = "My JavaFX Application"
        stage.scene = scene
        stage.show()
    }
}