/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
  id("kotlin")
  id("org.openjfx.javafxplugin") version "0.0.9"
  id("easyreading.kotlin-application-conventions")
}


javafx {
  version = "17.0.2"
  modules = listOf("javafx.controls")
}

dependencies {
  implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.6.4")
  implementation("org.jetbrains.kotlinx:kotlinx-coroutines-javafx:1.6.4")
  api(project(":utilities"))

}

application {
  // Define the main class for the application.
  mainClass.set("easyreading.app.AppKt")
}
