/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package vanity.app

import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.javafx.JavaFx
import kotlinx.coroutines.withContext
import org.koin.dsl.module
import vanity.app.apps.services.AppService

suspend fun main() = withContext(Dispatchers.JavaFx) {


    Vanity.start {
        listOf(
            VanityChest(
                "Some cool Apps",
                module {
                    single<IAppService> { AppService() }
                }
            )
        )

    }
}
