/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package vanity.app

import Vanity
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.javafx.JavaFx
import kotlinx.coroutines.withContext

suspend fun main() = withContext(Dispatchers.JavaFx) {
    Vanity.start { emptyList() }
}
