/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package vanity.app

import vanity.app.failurewindows.showError
import vanity.app.init.Init
import vanity.app.init.inject.Koin
import vanity.app.init.inject.getService
import vanity.app.init.services.IConfigurationService
import vanity.app.platformview.PlatformCoreView
import javafx.application.Application
import javafx.scene.Scene
import javafx.stage.Stage
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.javafx.JavaFx
import kotlinx.coroutines.withContext

suspend fun main() = withContext(Dispatchers.JavaFx) {
    Koin().start()
    Init(getService(), { message -> showError(message) }) { startPlatform() }
    Unit
}

private fun startPlatform() {
    val fxApp = PlatformApp()
    fxApp.start(Stage())
}

class PlatformApp : Application() {
    override fun start(stage: Stage) {
        val scene = Scene(PlatformCoreView(), 400.0, 300.0)
        scene.stylesheets.add(getService<IConfigurationService>().cssSheet)
        stage.title = "vanity Platform"
        stage.scene = scene
        stage.show()
    }
}