name: check

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - '**'

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: 17
          cache: gradle

      - name: check 
        run:  ./gradlew check

  release:
    needs: check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: 17
          cache: gradle
      - uses: extractions/setup-just@v1
      - run: just release
        env:
          GITHUB_USERNAME: SilenLoc
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}